sudo: false

language: python
dist: xenial
cache: pip

stages:
  - test Linux

env:
  global:
    - V=1
    - QUIET=

install:
  - make upgrade-wheel
  - make install-coverage
  - make install-tests

before_script:
  - git clone https://github.com/heilaaks/snippy.git
  - make -C snippy install
  - make -C snippy install-server
  - rm -rf snippy

script:
  - make tests

jobs:
  include:
    - name: Python 2.7
      python: 2.7
      stage: test Linux
    - name: Python 3.4
      python: 3.4
      stage: test Linux
    - name: Python 3.5
      python: 3.5
      stage: test Linux
    - name: Python 3.6
      python: 3.6
      stage: test Linux
    - name: Python 3.7
      python: 3.7
      stage: test Linux
    - name: Python 3.8
      python: 3.8-dev
      stage: test Linux
    - name: PyPy2
      python: pypy
      stage: test Linux
    - name: PyPy3
      python: pypy3
      stage: test Linux
    - name: lint python3
      python: 3.7
      stage: test Linux
      script:
        - make lint

after_success:
  - codecov
  - coveralls
